# The following code was generated by Deepseek
# Modification might be needed to get it work properly

# Add the ../../python directory to sys.path for importing evolink_test
import os
import sys
module_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../python"))
if module_path not in sys.path:
    sys.path.append(module_path)

from evolink_test import test_evolink_cmd

import requests
import re  # Import the Regular Expression module

# Ollama API endpoint
DEEPSEEK_API_URL = "http://192.168.0.107:11434/v1/chat/completions"


# Your API key
API_KEY = "your_api_key_here"

# Set the request headers, including the API key
headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}

# Define the prompt to send to the model
prompt = "讲一个笑话，回答不要超过50字。"

# Build the request body
data = {
    "model": "deepseek-r1:32b",  # Replace with the DeepSeek model name you want to use
    "messages": [
        {"role": "user", "content": prompt}
    ],
    "stream": False  # Make sure streaming is disabled and the full result is returned
}

# Send the POST request to the DeepSeek API
response = requests.post(DEEPSEEK_API_URL, json=data)

# Check response status code
if response.status_code == 200:
    # Parse the response
    result = response.json()
    # Extract the model's reply
    model_reply = result['choices'][0]['message']['content']
    
    # Remove <think></think> tags and their content
    cleaned_reply = re.sub(r'<think>.*?</think>', '', model_reply, flags=re.DOTALL)
    
    # Remove extra spaces and newlines
    cleaned_reply = cleaned_reply.strip()
    
cmd_interrupt = {
    "command": "speak",
    'binary_content_length': 0,
    "content": {
        'id': -1,
        'text': cleaned_reply,
        'face_driver': 'arkit',
        'body_driver': 'emote',
        'face_data_length': 0,
        'body_data_length': 0,
        'audio_data_length': 0,
        'interrupt': True,
        'frame_rate': 0,
        'animations': [
            {
                'timestamp': 0.0,
                'body_anim_sku': 'TALK',
                'loop': False,
                'blend': 0.5
            }
        ]
    }
}

if __name__ == "__main__":
    test_evolink_cmd(cmd_interrupt, True, [])
